spring:
  datasource:
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
    url: ${DB_URL:jdbc:postgresql://localhost:5432/micr-synch}
    username: ${DB_USERNAME:qwe}
    password: ${DB_PASSWORD:qwe}

  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    enabled: ${FLYWAY_ENABLED:true}

  application:
    name: ${APP_NAME:bucket}

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL:http://localhost:9411/api/v2/spans}
  endpoints:
    web:
      exposure:
        include: health,info,metrics,tracing

logging:
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    root: info
    org.springframework: warn
    com.zaxxer.hikari: warn
    org.hibernate: warn
    com.netflix.discovery: warn
    com.serjnn: info

services:
  product:
    url: ${PRODUCT_SERVICE_URL:http://product/api/v1/products/by-ids}

server:
  port: ${PORT:7001}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
    register-with-eureka: ${EUREKA_REGISTER:true}
    fetch-registry: ${EUREKA_FETCH:true}
  instance:
    instance-id: ${spring.application.name}:${server.port}:${random.value}
    prefer-ip-address: ${EUREKA_PREFER_IP:true}

springdoc:
  api-docs:
    path: ${API_DOCS_PATH:/v3/api-docs}
  swagger-ui:
    path: ${SWAGGER_UI_PATH:/swagger-ui.html}
    enabled: ${SWAGGER_ENABLED:true}
