spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/micr-synch
    username: ${POSTGRES_USER:qwe}
    password: ${POSTGRES_PASSWORD:qwe}

  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    enabled: true

  application:
    name: Bucket

server:
  port: 7001



